name: storage_ui
description: A powerful and user-friendly library for managing saved key-value pairs in Flutter, built on top of get_storage and flutter_secure_storage.
version: 1.0.0+1
homepage: "https://github.com/AmrSaied/storage_ui"

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_storage:
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
